// Generated by scripts/photos.mjs — edit the selection there and re-run.
// Photographs by Manas Thakur (@menace_thakur on Instagram).

export type Photo = {
  slug: string;
  w: number;
  h: number;
  alt: string;
  /** Manas's own caption from the post, when he wrote one. */
  caption: string;
  place: string;
  date: string;
  iso: string;
  post: string;
  /** Up to five colours sampled from the frame, most area first (content, not design tokens). */
  palette: string[];
  /** OKLCH hue (0–360) and chroma of the frame's most telling colour. */
  hue: number;
  chroma: number;
  /** Mean OKLab lightness, 0–1. */
  light: number;
  /** How colourful the frame is relative to the roll: 0 (grey) to 1 (most vivid). */
  sat: number;
};

export const instagram = 'https://www.instagram.com/menace_thakur/';

export const photoSrc = (slug: string, size: 'xs' | 'sm' | 'lg') => `/photos/${slug}-${size}.webp`;

export const photos: Photo[] = [
  {
    "slug": "crimson-sky",
    "w": 1440,
    "h": 1440,
    "alt": "A blood-red evening sky smeared above dark rooftops",
    "caption": "",
    "place": "",
    "date": "Aug 2024",
    "iso": "2024-08-19",
    "post": "https://www.instagram.com/p/C-2w7DqyO5j/",
    "palette": [
      "#321e31",
      "#080406",
      "#471f2b",
      "#62232c",
      "#a32429"
    ],
    "hue": 22,
    "chroma": 0.145,
    "light": 0.266,
    "sat": 0.649
  },
  {
    "slug": "peacock",
    "w": 1080,
    "h": 1080,
    "alt": "A peacock crossing a sandy garden path",
    "caption": "",
    "place": "Delhi",
    "date": "Jun 2024",
    "iso": "2024-06-05",
    "post": "https://www.instagram.com/p/C72D35USH5N/",
    "palette": [
      "#a39c84",
      "#babda1",
      "#857c5f",
      "#21251a",
      "#90ac71"
    ],
    "hue": 129,
    "chroma": 0.087,
    "light": 0.6,
    "sat": 0.338
  },
  {
    "slug": "blossom-bus",
    "w": 1440,
    "h": 1440,
    "alt": "A yellow school bus parked beneath a cherry tree in full bloom",
    "caption": "",
    "place": "South Korea",
    "date": "Apr 2026",
    "iso": "2026-04-04",
    "post": "https://www.instagram.com/p/DWtpI8CEfkP/",
    "palette": [
      "#504637",
      "#7d7e73",
      "#635f59",
      "#95a5b6",
      "#8b7826"
    ],
    "hue": 96,
    "chroma": 0.1,
    "light": 0.501,
    "sat": 0.296
  },
  {
    "slug": "lotus-temple",
    "w": 1080,
    "h": 1080,
    "alt": "The Lotus Temple rising beyond a wide green lawn",
    "caption": "",
    "place": "Lotus Temple, New Delhi",
    "date": "Mar 2024",
    "iso": "2024-03-23",
    "post": "https://www.instagram.com/p/C424cCYyeyt/",
    "palette": [
      "#a5b3c4",
      "#516336",
      "#8697ac",
      "#2a3c19",
      "#e5ebf2"
    ],
    "hue": 129,
    "chroma": 0.094,
    "light": 0.583,
    "sat": 0.478
  },
  {
    "slug": "rain-umbrella",
    "w": 3072,
    "h": 3072,
    "alt": "A figure under a pale umbrella on a rain-soaked night path",
    "caption": "",
    "place": "South Korea",
    "date": "Apr 2026",
    "iso": "2026-04-17",
    "post": "https://www.instagram.com/p/DXPEaflEZ60/",
    "palette": [
      "#171715",
      "#060504",
      "#000000",
      "#424b2b",
      "#4b611b"
    ],
    "hue": 125,
    "chroma": 0.096,
    "light": 0.172,
    "sat": 0.229
  },
  {
    "slug": "lion-capital",
    "w": 1080,
    "h": 1080,
    "alt": "A gilded Ashoka lion capital lit up at night",
    "caption": "Aditya engineering college campus",
    "place": "SIH 2023 finale trip",
    "date": "Dec 2023",
    "iso": "2023-12-22",
    "post": "https://www.instagram.com/p/C1Ka9-_SgWC/",
    "palette": [
      "#211f1a",
      "#0d0b0c",
      "#866343",
      "#483b2d",
      "#bb9a5a"
    ],
    "hue": 82,
    "chroma": 0.092,
    "light": 0.335,
    "sat": 0.397
  },
  {
    "slug": "keyboard-moth",
    "w": 1440,
    "h": 1920,
    "alt": "A moth resting on the keys of a cream mechanical keyboard",
    "caption": "end of august",
    "place": "",
    "date": "Sept 2026",
    "iso": "2026-09-05",
    "post": "https://www.instagram.com/p/Dc6f2MHk4LQ/",
    "palette": [
      "#c5c2b0",
      "#73685c",
      "#a39e8c",
      "#090405",
      "#652310"
    ],
    "hue": 36,
    "chroma": 0.099,
    "light": 0.525,
    "sat": 0.248
  },
  {
    "slug": "river-sunset",
    "w": 1440,
    "h": 1440,
    "alt": "A pink sunset over a shallow river, mountains and apartment towers beyond",
    "caption": "",
    "place": "South Korea",
    "date": "Mar 2026",
    "iso": "2026-03-20",
    "post": "https://www.instagram.com/p/DWHhmLskwQx/",
    "palette": [
      "#090607",
      "#4f2a24",
      "#824234",
      "#2f1b16",
      "#000000"
    ],
    "hue": 32,
    "chroma": 0.087,
    "light": 0.234,
    "sat": 0.459
  },
  {
    "slug": "madhubani",
    "w": 1080,
    "h": 1080,
    "alt": "Madhubani-style elephants drawn in fine black line on a white wall",
    "caption": "",
    "place": "Delhi",
    "date": "Jun 2024",
    "iso": "2024-06-05",
    "post": "https://www.instagram.com/p/C72FAD0SSlj/",
    "palette": [
      "#766c6a",
      "#635857",
      "#8e8381",
      "#a49996",
      "#504644"
    ],
    "hue": 24,
    "chroma": 0.068,
    "light": 0.544,
    "sat": 0
  },
  {
    "slug": "night-blossoms",
    "w": 1440,
    "h": 1440,
    "alt": "Cherry blossoms glowing white against a black night sky",
    "caption": "",
    "place": "South Korea",
    "date": "Mar 2026",
    "iso": "2026-03-29",
    "post": "https://www.instagram.com/p/DWeTlmVkXzg/",
    "palette": [
      "#020307",
      "#2e2c2c",
      "#4d4b48",
      "#141415",
      "#787977"
    ],
    "hue": 62,
    "chroma": 0.051,
    "light": 0.272,
    "sat": 0
  },
  {
    "slug": "amaltas",
    "w": 1080,
    "h": 1080,
    "alt": "Golden amaltas blossoms hanging against a pale sky",
    "caption": "Yellow:)",
    "place": "",
    "date": "May 2024",
    "iso": "2024-05-23",
    "post": "https://www.instagram.com/p/C7TgRRvyNWc/",
    "palette": [
      "#9b7d37",
      "#74642f",
      "#afadbd",
      "#b6973a",
      "#51411d"
    ],
    "hue": 84,
    "chroma": 0.111,
    "light": 0.599,
    "sat": 0.778
  },
  {
    "slug": "claw-machines",
    "w": 1440,
    "h": 1440,
    "alt": "A row of claw machines glowing neon green",
    "caption": "",
    "place": "South Korea",
    "date": "Mar 2026",
    "iso": "2026-03-24",
    "post": "https://www.instagram.com/p/DWRn-ijk17h/",
    "palette": [
      "#163b24",
      "#3b5b3c",
      "#052013",
      "#010a04",
      "#095b21"
    ],
    "hue": 148,
    "chroma": 0.114,
    "light": 0.325,
    "sat": 0.662
  },
  {
    "slug": "butterfly-cat",
    "w": 1440,
    "h": 1440,
    "alt": "An orange butterfly in sharp focus in front of a tabby cat",
    "caption": "somewhere out there a cat has a favorite human",
    "place": "",
    "date": "Mar 2026",
    "iso": "2026-03-07",
    "post": "https://www.instagram.com/p/DVlh6qFkb8f/",
    "palette": [
      "#61503a",
      "#3e391d",
      "#806a42",
      "#a8934c",
      "#b27b0f"
    ],
    "hue": 76,
    "chroma": 0.125,
    "light": 0.449,
    "sat": 0.628
  },
  {
    "slug": "hill-roofs",
    "w": 1440,
    "h": 1080,
    "alt": "Red roofs and green hills under a bright cloudy sky",
    "caption": "September :)",
    "place": "",
    "date": "Oct 2026",
    "iso": "2026-10-01",
    "post": "https://www.instagram.com/p/Dd81odsEzXd/",
    "palette": [
      "#1c2716",
      "#41513f",
      "#aab4c8",
      "#6788b4",
      "#ca4d61"
    ],
    "hue": 14,
    "chroma": 0.163,
    "light": 0.494,
    "sat": 0.719
  },
  {
    "slug": "wing-sunrise",
    "w": 1080,
    "h": 1350,
    "alt": "The sun rising over cloud seen past an aircraft wing",
    "caption": "Morning Sunshine...",
    "place": "SIH 2023 finale trip",
    "date": "Dec 2023",
    "iso": "2023-12-22",
    "post": "https://www.instagram.com/p/C1Kaf1gy_PC/",
    "palette": [
      "#45291c",
      "#2b1005",
      "#713f29",
      "#a9673d",
      "#9e440d"
    ],
    "hue": 44,
    "chroma": 0.132,
    "light": 0.405,
    "sat": 0.789
  },
  {
    "slug": "lotus-ceiling",
    "w": 1080,
    "h": 1080,
    "alt": "The petalled ceiling inside the Lotus Temple",
    "caption": "",
    "place": "Lotus Temple, New Delhi",
    "date": "Mar 2024",
    "iso": "2024-03-23",
    "post": "https://www.instagram.com/p/C424OFFSPJk/",
    "palette": [
      "#95887f",
      "#877c74",
      "#a19c96",
      "#6a625d",
      "#c7d2d6"
    ],
    "hue": 59,
    "chroma": 0.053,
    "light": 0.628,
    "sat": 0
  },
  {
    "slug": "marigolds",
    "w": 1080,
    "h": 1080,
    "alt": "A bed of bright yellow marigolds",
    "caption": "flouər for some beautiful people..",
    "place": "",
    "date": "Mar 2024",
    "iso": "2024-03-23",
    "post": "https://www.instagram.com/p/C424cCYyeyt/",
    "palette": [
      "#161f07",
      "#303f12",
      "#a09311",
      "#e5bd06",
      "#cca907"
    ],
    "hue": 94,
    "chroma": 0.151,
    "light": 0.476,
    "sat": 1
  },
  {
    "slug": "brick-ruin",
    "w": 1080,
    "h": 1080,
    "alt": "A weathered red-brick ruin with arched niches beside a lawn",
    "caption": "",
    "place": "Delhi",
    "date": "Jun 2024",
    "iso": "2024-06-05",
    "post": "https://www.instagram.com/p/C72D35USH5N/",
    "palette": [
      "#6d523f",
      "#64893f",
      "#bcb7b0",
      "#8d7561",
      "#413327"
    ],
    "hue": 132,
    "chroma": 0.113,
    "light": 0.555,
    "sat": 0.546
  },
  {
    "slug": "flyover-sun",
    "w": 1440,
    "h": 1080,
    "alt": "An orange sun sinking behind a flyover silhouette",
    "caption": "",
    "place": "",
    "date": "Aug 2024",
    "iso": "2024-08-31",
    "post": "https://www.instagram.com/p/C_U74epygkE/",
    "palette": [
      "#020202",
      "#070706",
      "#120f0d",
      "#3b2f2a",
      "#a06031"
    ],
    "hue": 55,
    "chroma": 0.109,
    "light": 0.184,
    "sat": 0.324
  },
  {
    "slug": "cloud-tower",
    "w": 1440,
    "h": 1440,
    "alt": "A towering cloud lit gold from the side above the city",
    "caption": "",
    "place": "",
    "date": "Aug 2024",
    "iso": "2024-08-19",
    "post": "https://www.instagram.com/p/C-2w7DqyO5j/",
    "palette": [
      "#3d3e43",
      "#604b45",
      "#242122",
      "#b7845b",
      "#050505"
    ],
    "hue": 57,
    "chroma": 0.084,
    "light": 0.365,
    "sat": 0.187
  },
  {
    "slug": "petal-heart",
    "w": 1440,
    "h": 1440,
    "alt": "A heart traced in a carpet of fallen cherry petals",
    "caption": "",
    "place": "South Korea",
    "date": "Apr 2026",
    "iso": "2026-04-04",
    "post": "https://www.instagram.com/p/DWtqesEEQIz/",
    "palette": [
      "#837e7e",
      "#6e6967",
      "#979495",
      "#1f2626",
      "#4f4d4c"
    ],
    "hue": 53,
    "chroma": 0.052,
    "light": 0.529,
    "sat": 0
  },
  {
    "slug": "dcu",
    "w": 1440,
    "h": 1440,
    "alt": "The DCU sign at the Daegu Catholic University campus",
    "caption": "",
    "place": "Daegu Catholic University",
    "date": "Mar 2026",
    "iso": "2026-03-23",
    "post": "https://www.instagram.com/p/DWPKABuk965/",
    "palette": [
      "#050b12",
      "#1a252e",
      "#000001",
      "#87949e",
      "#a16b36"
    ],
    "hue": 63,
    "chroma": 0.097,
    "light": 0.269,
    "sat": 0.162
  },
  {
    "slug": "felt-sheep",
    "w": 1440,
    "h": 1440,
    "alt": "Three felt sheep lined up on a shelf",
    "caption": "",
    "place": "South Korea",
    "date": "Apr 2026",
    "iso": "2026-04-13",
    "post": "https://www.instagram.com/p/DXECF7METwt/",
    "palette": [
      "#a8aaa5",
      "#939b9f",
      "#684d36",
      "#7a7671",
      "#3e2614"
    ],
    "hue": 53,
    "chroma": 0.083,
    "light": 0.619,
    "sat": 0.248
  },
  {
    "slug": "batmobile",
    "w": 1440,
    "h": 1440,
    "alt": "A toy Batman riding a purple Batmobile against a red wall",
    "caption": "",
    "place": "",
    "date": "Apr 2025",
    "iso": "2025-04-15",
    "post": "https://www.instagram.com/p/DIc-9BNRLXs/",
    "palette": [
      "#843431",
      "#c5b69e",
      "#21111b",
      "#403853",
      "#71768b"
    ],
    "hue": 25,
    "chroma": 0.114,
    "light": 0.505,
    "sat": 0.772
  },
  {
    "slug": "goose",
    "w": 843,
    "h": 1053,
    "alt": "A white goose standing on bare earth beneath trees",
    "caption": "Wanna be this chill in life🥲",
    "place": "",
    "date": "Jan 2024",
    "iso": "2024-01-01",
    "post": "https://www.instagram.com/p/C1jeN7lyy9C/",
    "palette": [
      "#51473a",
      "#d4d4d9",
      "#333028",
      "#101714",
      "#743f2b"
    ],
    "hue": 41,
    "chroma": 0.08,
    "light": 0.481,
    "sat": 0.094
  },
  {
    "slug": "arched-corridor",
    "w": 1080,
    "h": 1080,
    "alt": "A long arched corridor lined with glowing lights, shot from floor level",
    "caption": "Aditya engineering college campus",
    "place": "SIH 2023 finale trip",
    "date": "Dec 2023",
    "iso": "2023-12-22",
    "post": "https://www.instagram.com/p/C1Ka9-_SgWC/",
    "palette": [
      "#ad9573",
      "#8e7759",
      "#443f32",
      "#685b47",
      "#c6b291"
    ],
    "hue": 74,
    "chroma": 0.058,
    "light": 0.579,
    "sat": 0.397
  },
  {
    "slug": "gulmohar",
    "w": 1080,
    "h": 1080,
    "alt": "Red gulmohar flowers among feathery green leaves against a blue sky",
    "caption": "In spring’s song, birds chirp poetry, painting the air with a melody beyond compare...",
    "place": "",
    "date": "Apr 2024",
    "iso": "2024-04-19",
    "post": "https://www.instagram.com/p/C58bgw2yOUs/",
    "palette": [
      "#505138",
      "#393c2a",
      "#6d6c50",
      "#898d7b",
      "#8e4536"
    ],
    "hue": 34,
    "chroma": 0.102,
    "light": 0.505,
    "sat": 0.459
  },
  {
    "slug": "duck",
    "w": 1080,
    "h": 1350,
    "alt": "A duck perched on a floating log in rippling green water",
    "caption": "Quick quack...",
    "place": "Delhi",
    "date": "Jun 2024",
    "iso": "2024-06-05",
    "post": "https://www.instagram.com/p/C72DmdQy9W9/",
    "palette": [
      "#9ea5a9",
      "#b6bdbe",
      "#232b20",
      "#444f46",
      "#757e7a"
    ],
    "hue": 136,
    "chroma": 0.06,
    "light": 0.574,
    "sat": 0
  },
  {
    "slug": "violet-dusk",
    "w": 1440,
    "h": 1440,
    "alt": "A violet storm sky glowing pink at the horizon above city rooftops",
    "caption": "",
    "place": "",
    "date": "Aug 2024",
    "iso": "2024-08-19",
    "post": "https://www.instagram.com/p/C-2w7DqyO5j/",
    "palette": [
      "#2d2541",
      "#4b3960",
      "#17141f",
      "#07060a",
      "#824d6f"
    ],
    "hue": 297,
    "chroma": 0.069,
    "light": 0.292,
    "sat": 0.496
  },
  {
    "slug": "poodle",
    "w": 1440,
    "h": 1440,
    "alt": "A small white curly-haired dog with a yellow collar, held in someone’s arms on a street",
    "caption": "",
    "place": "South Korea",
    "date": "Mar 2026",
    "iso": "2026-03-24",
    "post": "https://www.instagram.com/p/DWRn-ijk17h/",
    "palette": [
      "#837a70",
      "#d3d0c1",
      "#b6a08a",
      "#47453e",
      "#b88c37"
    ],
    "hue": 76,
    "chroma": 0.103,
    "light": 0.589,
    "sat": 0.296
  },
  {
    "slug": "night-street",
    "w": 1440,
    "h": 1920,
    "alt": "A narrow street at dusk under a purple sky, streetlights glowing beside an elevated railway",
    "caption": "",
    "place": "South Korea",
    "date": "Mar 2026",
    "iso": "2026-03-20",
    "post": "https://www.instagram.com/p/DWHjSnSE-qh/",
    "palette": [
      "#000000",
      "#3e3556",
      "#120e0b",
      "#020202",
      "#302125"
    ],
    "hue": 283,
    "chroma": 0.081,
    "light": 0.168,
    "sat": 0.338
  },
  {
    "slug": "pink-tree",
    "w": 1440,
    "h": 1440,
    "alt": "A tree heavy with deep-pink blossoms above green grass",
    "caption": "",
    "place": "South Korea",
    "date": "Apr 2026",
    "iso": "2026-04-13",
    "post": "https://www.instagram.com/p/DXECF7METwt/",
    "palette": [
      "#5c473b",
      "#7f6650",
      "#392d26",
      "#17160f",
      "#a19168"
    ],
    "hue": 16,
    "chroma": 0.067,
    "light": 0.411,
    "sat": 0.468
  },
  {
    "slug": "calico-cat",
    "w": 1440,
    "h": 1440,
    "alt": "A calico cat lounging on wooden boards, looking straight at the camera",
    "caption": "",
    "place": "South Korea",
    "date": "Apr 2026",
    "iso": "2026-04-17",
    "post": "https://www.instagram.com/p/DXPEaflEZ60/",
    "palette": [
      "#bda386",
      "#8b7b68",
      "#61564b",
      "#e1d1bb",
      "#312921"
    ],
    "hue": 67,
    "chroma": 0.087,
    "light": 0.61,
    "sat": 0.35
  },
  {
    "slug": "rgb-keyboard",
    "w": 1440,
    "h": 1920,
    "alt": "A mechanical keyboard glowing in rainbow backlight in a dark room",
    "caption": "",
    "place": "",
    "date": "Apr 2026",
    "iso": "2026-04-06",
    "post": "https://www.instagram.com/p/DWzEk1rE7GP/",
    "palette": [
      "#060608",
      "#161718",
      "#000000",
      "#2f2f3c",
      "#162495"
    ],
    "hue": 268,
    "chroma": 0.174,
    "light": 0.177,
    "sat": 0.35
  },
  {
    "slug": "misty-hills",
    "w": 1440,
    "h": 810,
    "alt": "Mist rolling over green hills scattered with houses",
    "caption": "September :)",
    "place": "",
    "date": "Oct 2026",
    "iso": "2026-10-01",
    "post": "https://www.instagram.com/p/Dd81odsEzXd/",
    "palette": [
      "#4f697a",
      "#8f9fb4",
      "#334d3e",
      "#526a3d",
      "#798845"
    ],
    "hue": 127,
    "chroma": 0.106,
    "light": 0.549,
    "sat": 0.429
  },
  {
    "slug": "bougainvillea",
    "w": 1440,
    "h": 1440,
    "alt": "Magenta bougainvillea spilling over a wall beside a residential street",
    "caption": "",
    "place": "",
    "date": "Feb 2025",
    "iso": "2025-02-26",
    "post": "https://www.instagram.com/p/DGiXgXET-31/",
    "palette": [
      "#2a1d19",
      "#382a25",
      "#1b1210",
      "#52423f",
      "#531520"
    ],
    "hue": 15,
    "chroma": 0.09,
    "light": 0.279,
    "sat": 0.229
  }
];
